#cloud-config
# Desktop + Guacamole Combined Server
# Provides: xRDP Desktop + Guacamole Web Access

package_update: true
package_upgrade: true

packages:
  - htop
  - curl
  - wget
  - jq
  - docker.io
  - docker-compose
  - xrdp
  - xfce4
  - xfce4-goodies
  - dbus-x11
  - python3

chpasswd:
  expire: false
  users:
    - name: root
      password: ${root_password}
  encrypted: false

ssh_pwauth: true

write_files:
  # Docker compose for Guacamole (v2.4 for docker-compose v1.x compatibility)
  - path: /opt/guacamole/docker-compose.yml
    permissions: '0644'
    content: |
      version: '2.4'
      
      services:
        guacd:
          image: guacamole/guacd:latest
          container_name: guacd
          restart: always
          networks:
            - guacamole-net
        
        postgres:
          image: postgres:15-alpine
          container_name: guacamole-postgres
          restart: always
          environment:
            POSTGRES_DB: guacamole
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guacamole_db_password}
          volumes:
            - postgres-data:/var/lib/postgresql/data
            - /opt/guacamole/initdb:/docker-entrypoint-initdb.d:ro
          networks:
            - guacamole-net
        
        guacamole:
          image: guacamole/guacamole:latest
          container_name: guacamole
          restart: always
          depends_on:
            - postgres
            - guacd
          environment:
            GUACD_HOSTNAME: guacd
            POSTGRES_HOSTNAME: postgres
            POSTGRES_DATABASE: guacamole
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guacamole_db_password}
          ports:
            - "8080:8080"
          networks:
            - guacamole-net
      
      networks:
        guacamole-net:
          driver: bridge
      
      volumes:
        postgres-data:

  # Guacamole database init script generator
  - path: /opt/guacamole/install.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      
      echo "=== Generating Guacamole database schema ==="
      mkdir -p /opt/guacamole/initdb
      
      # Generate schema SQL
      docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > /opt/guacamole/initdb/01-schema.sql
      
      echo "=== Schema files generated ==="
      ls -la /opt/guacamole/initdb/

  # Status server for health checks (unified with systemd)
  - path: /opt/swiss365/status-server.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """Swiss365 Unified Status Server for Desktop/Guacamole"""
      import http.server
      import json
      import subprocess
      import os
      import hashlib
      import hmac
      import time
      from urllib.parse import urlparse
      from datetime import datetime
      
      STATUS_PORT = 8081
      AGENT_PORT = 9365
      AGENT_SECRET = "${agent_secret}"

      def run_cmd(cmd, timeout=30):
          try:
              result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)
              return result.stdout.strip(), result.returncode
          except Exception as e:
              return str(e), 1

      def get_docker_status():
          containers = []
          output, _ = run_cmd("docker ps -a --format '{{.Names}}|{{.Status}}|{{.Image}}'")
          for line in output.split('\n'):
              if '|' in line:
                  parts = line.split('|')
                  containers.append({
                      'name': parts[0],
                      'status': parts[1],
                      'image': parts[2] if len(parts) > 2 else ''
                  })
          return containers

      def get_system_metrics():
          cpu, _ = run_cmd("top -bn1 | grep 'Cpu(s)' | awk '{print $2}'")
          mem, _ = run_cmd("free -m | awk 'NR==2{printf \"%.1f\", $3*100/$2}'")
          disk, _ = run_cmd("df -h / | awk 'NR==2{print $5}' | tr -d '%'")
          return {'cpu': cpu, 'memory': mem, 'disk': disk}

      def get_guacamole_health():
          # Check Guacamole HTTP
          status, _ = run_cmd("curl -s -o /dev/null -w '%%{http_code}' http://localhost:8080/guacamole/ 2>/dev/null || echo '0'")
          # Check critical containers
          guacamole, _ = run_cmd("docker ps -q -f name=guacamole -f status=running")
          guacd, _ = run_cmd("docker ps -q -f name=guacd -f status=running")
          postgres, _ = run_cmd("docker ps -q -f name=guacamole-postgres -f status=running")
          # Check xRDP
          xrdp, _ = run_cmd("systemctl is-active xrdp")
          return {
              'guacamole_responding': status == '200',
              'guacamole_running': bool(guacamole),
              'guacd_running': bool(guacd),
              'postgres_running': bool(postgres),
              'xrdp_running': xrdp == 'active'
          }

      def get_install_logs():
          logs = []
          log_file = '/var/log/swiss365/install.log'
          if os.path.exists(log_file):
              with open(log_file, 'r') as f:
                  logs = f.readlines()[-100:]
          return [l.strip() for l in logs]

      class StatusHandler(http.server.BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              pass

          def send_json(self, data, status=200):
              self.send_response(status)
              self.send_header('Content-Type', 'application/json')
              self.send_header('Access-Control-Allow-Origin', '*')
              self.end_headers()
              self.wfile.write(json.dumps(data).encode())

          def do_GET(self):
              path = urlparse(self.path).path
              
              if path == '/health':
                  self.send_json({'status': 'ok', 'service': 'desktop_guacamole'})
              elif path == '/status' or path == '/':
                  health = get_guacamole_health()
                  self.send_json({
                      'service': 'desktop_guacamole',
                      'customer_id': '${customer_id}',
                      'timestamp': time.time(),
                      'healthy': health['guacamole_responding'] and health['xrdp_running'],
                      'health': health,
                      'docker': get_docker_status(),
                      'metrics': get_system_metrics()
                  })
              elif path == '/docker':
                  self.send_json({'containers': get_docker_status()})
              elif path == '/metrics':
                  self.send_json(get_system_metrics())
              elif path == '/logs':
                  self.send_json({'logs': get_install_logs()})
              else:
                  self.send_json({'error': 'Not found'}, 404)

          def do_OPTIONS(self):
              self.send_response(200)
              self.send_header('Access-Control-Allow-Origin', '*')
              self.send_header('Access-Control-Allow-Methods', 'GET, OPTIONS')
              self.end_headers()

      class AgentHandler(http.server.BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              pass

          def verify_signature(self):
              sig = self.headers.get('X-Signature', '')
              content_length = int(self.headers.get('Content-Length', 0))
              body = self.rfile.read(content_length).decode() if content_length > 0 else ''
              expected = hmac.new(AGENT_SECRET.encode(), body.encode(), hashlib.sha256).hexdigest()
              return hmac.compare_digest(sig, expected), body

          def send_json(self, data, status=200):
              self.send_response(status)
              self.send_header('Content-Type', 'application/json')
              self.send_header('Access-Control-Allow-Origin', '*')
              self.end_headers()
              self.wfile.write(json.dumps(data).encode())

          def do_OPTIONS(self):
              self.send_response(200)
              self.send_header('Access-Control-Allow-Origin', '*')
              self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
              self.send_header('Access-Control-Allow-Headers', 'Content-Type, X-Signature')
              self.end_headers()

          def do_POST(self):
              valid, body = self.verify_signature()
              if not valid:
                  self.send_json({'error': 'Invalid signature'}, 401)
                  return

              path = urlparse(self.path).path
              params = json.loads(body) if body else {}

              if path == '/restart':
                  service = params.get('service', 'all')
                  if service == 'all':
                      output, code = run_cmd('cd /opt/guacamole && docker-compose restart')
                  elif service == 'xrdp':
                      output, code = run_cmd('systemctl restart xrdp')
                  else:
                      output, code = run_cmd(f'docker restart {service}')
                  self.send_json({'success': code == 0, 'output': output})
              elif path == '/logs':
                  service = params.get('service', '')
                  lines = params.get('lines', 100)
                  if service:
                      output, _ = run_cmd(f'docker logs --tail {lines} {service} 2>&1')
                  else:
                      output, _ = run_cmd(f'tail -n {lines} /var/log/swiss365/install.log')
                  self.send_json({'logs': output})
              elif path == '/execute':
                  cmd = params.get('command', '')
                  if cmd in ['docker-compose up -d', 'docker-compose down', 'docker-compose restart']:
                      output, code = run_cmd(f'cd /opt/guacamole && {cmd}')
                      self.send_json({'success': code == 0, 'output': output})
                  else:
                      self.send_json({'error': 'Command not allowed'}, 403)
              else:
                  self.send_json({'error': 'Not found'}, 404)

      if __name__ == '__main__':
          import threading
          
          status_server = http.server.HTTPServer(('0.0.0.0', STATUS_PORT), StatusHandler)
          status_thread = threading.Thread(target=status_server.serve_forever)
          status_thread.daemon = True
          status_thread.start()
          print(f"Status server running on port {STATUS_PORT}")
          
          agent_server = http.server.HTTPServer(('0.0.0.0', AGENT_PORT), AgentHandler)
          print(f"Agent server running on port {AGENT_PORT}")
          agent_server.serve_forever()

  # Systemd service for status server
  - path: /etc/systemd/system/swiss365-status.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Swiss365 Status Server
      After=network.target docker.service

      [Service]
      Type=simple
      ExecStart=/usr/bin/python3 /opt/swiss365/status-server.py
      Restart=always
      RestartSec=5
      StandardOutput=append:/var/log/swiss365/status-server.log
      StandardError=append:/var/log/swiss365/status-server.log

      [Install]
      WantedBy=multi-user.target

  # Installation callback script
  - path: /usr/local/bin/swiss365-callback
    permissions: '0755'
    content: |
      #!/bin/bash
      STATUS="$1"
      STEP="$2"
      PROGRESS="$3"
      DETAILS="$4"
      
      CALLBACK_URL="${callback_url}"
      
      mkdir -p /var/log/swiss365
      echo "$(date '+%Y-%m-%d %H:%M:%S') [$STATUS] $STEP ($PROGRESS%) - $DETAILS" >> /var/log/swiss365/install.log
      
      if [ -n "$CALLBACK_URL" ]; then
        curl -s -X POST "$CALLBACK_URL" \
          -H "Content-Type: application/json" \
          -d "{
            \"workspace_id\": \"${customer_id}\",
            \"server_type\": \"desktop_guacamole\",
            \"status\": \"$STATUS\",
            \"current_step\": \"$STEP\",
            \"progress\": $PROGRESS,
            \"details\": \"$DETAILS\",
            \"server_ip\": \"$(hostname -I | awk '{print $1}')\"
          }" || true
      fi

runcmd:
  # Create log directories
  - mkdir -p /var/log/swiss365
  - mkdir -p /opt/swiss365
  - mkdir -p /opt/guacamole
  - touch /var/log/swiss365/install.log
  
  # Send initial callback
  - swiss365-callback "installing" "init" 5 "Server boot completed"
  
  # Configure SSH
  - sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - swiss365-callback "installing" "ssh" 10 "SSH configured"
  
  # Configure xRDP
  - swiss365-callback "installing" "xrdp" 15 "Configuring xRDP desktop"
  - echo "xfce4-session" > /root/.xsession
  - chmod +x /root/.xsession
  - sed -i 's/^test -x/# test -x/' /etc/xrdp/startwm.sh
  - echo "startxfce4" >> /etc/xrdp/startwm.sh
  - systemctl enable xrdp
  - systemctl start xrdp
  - swiss365-callback "installing" "xrdp" 25 "xRDP desktop ready"
  
  # Setup Docker
  - swiss365-callback "installing" "docker" 30 "Configuring Docker"
  - systemctl enable docker
  - systemctl start docker
  - swiss365-callback "installing" "docker" 35 "Docker running"
  
  # Generate Guacamole schema
  - swiss365-callback "installing" "guacamole" 40 "Generating Guacamole database schema"
  - cd /opt/guacamole && bash install.sh
  - swiss365-callback "installing" "guacamole" 45 "Schema generated"
  
  # Start containers in sequence - first guacd and postgres
  - swiss365-callback "installing" "guacamole" 50 "Starting backend services"
  - cd /opt/guacamole && docker-compose up -d guacd postgres
  
  # Wait for PostgreSQL to be ready (real health check)
  - swiss365-callback "installing" "guacamole" 55 "Waiting for database"
  - |
    for i in {1..30}; do
      if docker exec guacamole-postgres pg_isready -U guacamole -d guacamole >/dev/null 2>&1; then
        echo "PostgreSQL is ready"
        break
      fi
      echo "Waiting for PostgreSQL... ($i/30)"
      sleep 5
    done
  - swiss365-callback "installing" "guacamole" 60 "Database ready"
  
  # Now start the guacamole web container
  - swiss365-callback "installing" "guacamole" 65 "Starting Guacamole web interface"
  - cd /opt/guacamole && docker-compose up -d guacamole
  
  # Real health check - wait for Guacamole to respond
  - swiss365-callback "installing" "healthcheck" 70 "Waiting for Guacamole to be ready"
  - |
    for i in {1..30}; do
      HTTP_CODE=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost:8080/guacamole/ 2>/dev/null || echo "000")
      if [ "$HTTP_CODE" = "200" ]; then
        swiss365-callback "installing" "healthcheck" 80 "Guacamole responding"
        break
      fi
      echo "Waiting for Guacamole... ($i/30) HTTP: $HTTP_CODE"
      sleep 10
    done
  
  # Configure local RDP connection in Guacamole
  - swiss365-callback "installing" "connections" 85 "Configuring RDP connections"
  - |
    sleep 5
    docker exec guacamole-postgres psql -U guacamole -d guacamole -c "
    INSERT INTO guacamole_connection (connection_name, protocol) 
    VALUES ('Local Desktop', 'rdp')
    ON CONFLICT DO NOTHING;
    
    INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
    SELECT c.connection_id, p.parameter_name, p.parameter_value
    FROM guacamole_connection c
    CROSS JOIN (VALUES 
      ('hostname', 'localhost'),
      ('port', '3389'),
      ('username', 'root'),
      ('password', '${root_password}'),
      ('security', 'any'),
      ('ignore-cert', 'true')
    ) AS p(parameter_name, parameter_value)
    WHERE c.connection_name = 'Local Desktop'
    ON CONFLICT DO NOTHING;
    
    INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
    SELECT e.entity_id, c.connection_id, 'READ'
    FROM guacamole_entity e, guacamole_connection c
    WHERE e.name = 'guacadmin' AND c.connection_name = 'Local Desktop'
    ON CONFLICT DO NOTHING;
    " 2>/dev/null || true
  
  # Start status server via systemd
  - swiss365-callback "installing" "status-server" 90 "Starting status server"
  - systemctl daemon-reload
  - systemctl enable swiss365-status
  - systemctl start swiss365-status
  
  # Configure firewall
  - ufw allow 22/tcp
  - ufw allow 3389/tcp
  - ufw allow 8080/tcp
  - ufw allow 8081/tcp
  - ufw allow 9365/tcp
  
  # Final health verification
  - |
    GUAC_CHECK=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost:8080/guacamole/ 2>/dev/null || echo "000")
    XRDP_CHECK=$(systemctl is-active xrdp)
    if [ "$GUAC_CHECK" = "200" ] && [ "$XRDP_CHECK" = "active" ]; then
      swiss365-callback "ready" "complete" 100 "Desktop + Guacamole ready"
    else
      swiss365-callback "error" "healthcheck" 95 "Services not ready (Guacamole: HTTP $GUAC_CHECK, xRDP: $XRDP_CHECK)"
    fi
  
  - echo "$(date '+%Y-%m-%d %H:%M:%S') Installation complete" >> /var/log/swiss365/install.log
