#cloud-config
packages:
  - htop
ssh_pwauth: true
chpasswd:
  list: |
    root:${root_password_hash}
  expire: False
  encrypted: true
%{ if extra_cloud_init != "" }
runcmd:
${extra_cloud_init}
%{ endif }
