#cloud-config
# Standard server cloud-init - installs basic packages and xrdp for RDP access

packages:
  - htop
  - xrdp
  - xfce4
  - xfce4-goodies
  - dbus-x11

# Enable SSH password authentication
ssh_pwauth: true

# Set root password (plaintext - Terraform passes plaintext password)
chpasswd:
  list: |
    root:${root_password}
  expire: False

runcmd:
  # Configure SSH for password authentication and root login
  - sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - |
    # Remove any override configs that might block password auth
    for f in /etc/ssh/sshd_config.d/*.conf; do
      if [ -f "$f" ]; then
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' "$f"
        sed -i 's/^PermitRootLogin no/PermitRootLogin yes/' "$f"
        sed -i 's/^PermitRootLogin prohibit-password/PermitRootLogin yes/' "$f"
      fi
    done
  - systemctl restart ssh
  # Create status endpoint for remote monitoring
  - mkdir -p /var/log/lovable-status
  - echo '{"status":"initializing","step":"ssh-configured","timestamp":"'$(date -Iseconds)'"}' > /var/log/lovable-status/current.json
  # Configure xrdp to use xfce4
  - echo "xfce4-session" > /root/.xsession
  - chmod +x /root/.xsession
  # Enable and start xrdp
  - systemctl enable xrdp
  - systemctl start xrdp
  # Final status
  - echo '{"status":"ready","step":"xrdp-running","timestamp":"'$(date -Iseconds)'"}' > /var/log/lovable-status/current.json
  - echo "$(date): Server setup completed" > /var/log/cloud-init-complete.log
