#cloud-config
# Standard server cloud-init - installs basic packages and xrdp for RDP access

packages:
  - htop
  - xrdp
  - xfce4
  - xfce4-goodies
  - dbus-x11

ssh_pwauth: true
chpasswd:
  list: |
    root:${root_password}
  expire: False

runcmd:
  # Configure xrdp to use xfce4
  - echo "xfce4-session" > /root/.xsession
  - chmod +x /root/.xsession
  # Enable and start xrdp
  - systemctl enable xrdp
  - systemctl start xrdp
  # Log completion
  - echo "$(date): Server setup completed" > /var/log/cloud-init-complete.log
