#cloud-config
# Central Nextcloud Server - Multi-Tenant Storage

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - curl

write_files:
  - path: /opt/nextcloud/docker-compose.yml
    permissions: '0644'
    content: |
      version: '3.8'
      
      services:
        db:
          image: mariadb:10.11
          container_name: nextcloud-db
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: ${db_password}
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: ${db_password}
          volumes:
            - db-data:/var/lib/mysql
          networks:
            - nextcloud-net
        
        redis:
          image: redis:alpine
          container_name: nextcloud-redis
          restart: always
          networks:
            - nextcloud-net
        
        nextcloud:
          image: nextcloud:28-apache
          container_name: nextcloud
          restart: always
          depends_on:
            - db
            - redis
          environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: ${db_password}
            REDIS_HOST: redis
            NEXTCLOUD_ADMIN_USER: admin
            NEXTCLOUD_ADMIN_PASSWORD: ${admin_password}
            NEXTCLOUD_TRUSTED_DOMAINS: ${nextcloud_domain}
            OVERWRITEPROTOCOL: https
          volumes:
            - nextcloud-data:/var/www/html
          ports:
            - "80:80"
          networks:
            - nextcloud-net
      
      networks:
        nextcloud-net:
          driver: bridge
      
      volumes:
        db-data:
        nextcloud-data:

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /opt/nextcloud
  - cd /opt/nextcloud && docker-compose up -d
  
  # Wait for Nextcloud to initialize
  - sleep 180
  
  # Enable user provisioning API
  - docker exec -u www-data nextcloud php occ app:enable provisioning_api
  - docker exec -u www-data nextcloud php occ app:enable user_ldap
  
  # Configure for multi-tenant
  - docker exec -u www-data nextcloud php occ config:system:set default_quota --value="5 GB"
