#cloud-config
# Central Nextcloud Server - Multi-Tenant Storage with Status Server
# IMPROVED: Docker-pull retry, admin login test, UFW activation

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - curl
  - jq
  - python3

write_files:
  - path: /opt/nextcloud/docker-compose.yml
    permissions: '0644'
    content: |
      version: '2.4'
      
      services:
        db:
          image: mariadb:10.11
          container_name: nextcloud-db
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: ${db_password}
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: ${db_password}
          volumes:
            - db-data:/var/lib/mysql
          networks:
            - nextcloud-net
        
        redis:
          image: redis:alpine
          container_name: nextcloud-redis
          restart: always
          networks:
            - nextcloud-net
        
        nextcloud:
          image: nextcloud:28-apache
          container_name: nextcloud
          restart: always
          depends_on:
            - db
            - redis
          environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: ${db_password}
            REDIS_HOST: redis
            NEXTCLOUD_ADMIN_USER: admin
            NEXTCLOUD_ADMIN_PASSWORD: ${admin_password}
            NEXTCLOUD_TRUSTED_DOMAINS: ${nextcloud_domain}
            OVERWRITEPROTOCOL: https
          volumes:
            - nextcloud-data:/var/www/html
          ports:
            - "80:80"
          networks:
            - nextcloud-net
      
      networks:
        nextcloud-net:
          driver: bridge
      
      volumes:
        db-data:
        nextcloud-data:

  - path: /opt/swiss365/status-server.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """Swiss365 Unified Status Server for Nextcloud"""
      import http.server
      import json
      import subprocess
      import os
      import hashlib
      import hmac
      import time
      from urllib.parse import urlparse, parse_qs

      STATUS_PORT = 8081
      AGENT_PORT = 9365
      AGENT_SECRET = "${agent_secret}"

      def run_cmd(cmd, timeout=30):
          try:
              result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)
              return result.stdout.strip(), result.returncode
          except Exception as e:
              return str(e), 1

      def get_docker_status():
          containers = []
          output, _ = run_cmd("docker ps -a --format '{{.Names}}|{{.Status}}|{{.Image}}'")
          for line in output.split('\n'):
              if '|' in line:
                  parts = line.split('|')
                  containers.append({
                      'name': parts[0],
                      'status': parts[1],
                      'image': parts[2] if len(parts) > 2 else ''
                  })
          return containers

      def get_system_metrics():
          cpu, _ = run_cmd("top -bn1 | grep 'Cpu(s)' | awk '{print $2}'")
          mem, _ = run_cmd("free -m | awk 'NR==2{printf \"%.1f\", $3*100/$2}'")
          disk, _ = run_cmd("df -h / | awk 'NR==2{print $5}' | tr -d '%'")
          return {'cpu': cpu, 'memory': mem, 'disk': disk}

      def get_nextcloud_health():
          # Check Nextcloud status endpoint
          status, _ = run_cmd("curl -s -o /dev/null -w '%%{http_code}' http://localhost/status.php 2>/dev/null || echo '0'")
          # Check critical containers
          nextcloud, _ = run_cmd("docker ps -q -f name=nextcloud -f status=running")
          db, _ = run_cmd("docker ps -q -f name=nextcloud-db -f status=running")
          redis, _ = run_cmd("docker ps -q -f name=nextcloud-redis -f status=running")
          return {
              'api_responding': status == '200',
              'nextcloud_running': bool(nextcloud),
              'db_running': bool(db),
              'redis_running': bool(redis)
          }

      def get_install_logs():
          logs = []
          log_file = '/var/log/swiss365/install.log'
          if os.path.exists(log_file):
              with open(log_file, 'r') as f:
                  logs = f.readlines()[-100:]
          return [l.strip() for l in logs]

      class StatusHandler(http.server.BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              pass

          def send_json(self, data, status=200):
              self.send_response(status)
              self.send_header('Content-Type', 'application/json')
              self.send_header('Access-Control-Allow-Origin', '*')
              self.end_headers()
              self.wfile.write(json.dumps(data).encode())

          def do_GET(self):
              path = urlparse(self.path).path
              
              if path == '/health':
                  self.send_json({'status': 'ok', 'service': 'nextcloud'})
              elif path == '/status':
                  health = get_nextcloud_health()
                  self.send_json({
                      'service': 'nextcloud',
                      'timestamp': time.time(),
                      'healthy': all(health.values()),
                      'health': health,
                      'docker': get_docker_status(),
                      'metrics': get_system_metrics()
                  })
              elif path == '/docker':
                  self.send_json({'containers': get_docker_status()})
              elif path == '/metrics':
                  self.send_json(get_system_metrics())
              elif path == '/logs':
                  self.send_json({'logs': get_install_logs()})
              else:
                  self.send_json({'error': 'Not found'}, 404)

      class AgentHandler(http.server.BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              pass

          def verify_signature(self):
              sig = self.headers.get('X-Signature', '')
              content_length = int(self.headers.get('Content-Length', 0))
              body = self.rfile.read(content_length).decode() if content_length > 0 else ''
              expected = hmac.new(AGENT_SECRET.encode(), body.encode(), hashlib.sha256).hexdigest()
              return hmac.compare_digest(sig, expected), body

          def send_json(self, data, status=200):
              self.send_response(status)
              self.send_header('Content-Type', 'application/json')
              self.send_header('Access-Control-Allow-Origin', '*')
              self.end_headers()
              self.wfile.write(json.dumps(data).encode())

          def do_OPTIONS(self):
              self.send_response(200)
              self.send_header('Access-Control-Allow-Origin', '*')
              self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
              self.send_header('Access-Control-Allow-Headers', 'Content-Type, X-Signature')
              self.end_headers()

          def do_POST(self):
              valid, body = self.verify_signature()
              if not valid:
                  self.send_json({'error': 'Invalid signature'}, 401)
                  return

              path = urlparse(self.path).path
              params = json.loads(body) if body else {}

              if path == '/restart':
                  service = params.get('service', 'all')
                  if service == 'all':
                      output, code = run_cmd('cd /opt/nextcloud && docker-compose restart')
                  else:
                      output, code = run_cmd(f'docker restart {service}')
                  self.send_json({'success': code == 0, 'output': output})
              elif path == '/logs':
                  service = params.get('service', '')
                  lines = params.get('lines', 100)
                  if service:
                      output, _ = run_cmd(f'docker logs --tail {lines} {service} 2>&1')
                  else:
                      output, _ = run_cmd(f'tail -n {lines} /var/log/swiss365/install.log')
                  self.send_json({'logs': output})
              elif path == '/occ':
                  cmd = params.get('command', '')
                  if cmd:
                      output, code = run_cmd(f'docker exec -u www-data nextcloud php occ {cmd}')
                      self.send_json({'success': code == 0, 'output': output})
                  else:
                      self.send_json({'error': 'No command provided'}, 400)
              elif path == '/execute':
                  cmd = params.get('command', '')
                  if cmd in ['docker-compose up -d', 'docker-compose down', 'docker-compose restart']:
                      output, code = run_cmd(f'cd /opt/nextcloud && {cmd}')
                      self.send_json({'success': code == 0, 'output': output})
                  else:
                      self.send_json({'error': 'Command not allowed'}, 403)
              else:
                  self.send_json({'error': 'Not found'}, 404)

      if __name__ == '__main__':
          import threading
          
          status_server = http.server.HTTPServer(('0.0.0.0', STATUS_PORT), StatusHandler)
          status_thread = threading.Thread(target=status_server.serve_forever)
          status_thread.daemon = True
          status_thread.start()
          print(f"Status server running on port {STATUS_PORT}")
          
          agent_server = http.server.HTTPServer(('0.0.0.0', AGENT_PORT), AgentHandler)
          print(f"Agent server running on port {AGENT_PORT}")
          agent_server.serve_forever()

  - path: /etc/systemd/system/swiss365-status.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Swiss365 Status Server
      After=network.target docker.service

      [Service]
      Type=simple
      ExecStart=/usr/bin/python3 /opt/swiss365/status-server.py
      Restart=always
      RestartSec=5
      StandardOutput=append:/var/log/swiss365/status-server.log
      StandardError=append:/var/log/swiss365/status-server.log

      [Install]
      WantedBy=multi-user.target

  - path: /usr/local/bin/swiss365-callback
    permissions: '0755'
    content: |
      #!/bin/bash
      STATUS=$1
      STEP=$2
      PROGRESS=$3
      DETAILS=$4
      
      CALLBACK_URL="${callback_url}"
      WORKSPACE_ID="${workspace_id}"
      SERVER_TYPE="nextcloud"
      
      mkdir -p /var/log/swiss365
      echo "$(date '+%Y-%m-%d %H:%M:%S') [$STATUS] $STEP ($PROGRESS%) - $DETAILS" >> /var/log/swiss365/install.log
      
      if [ -n "$CALLBACK_URL" ]; then
        curl -s -X POST "$CALLBACK_URL" \
          -H "Content-Type: application/json" \
          -d "{\"workspace_id\":\"$WORKSPACE_ID\",\"server_type\":\"$SERVER_TYPE\",\"status\":\"$STATUS\",\"current_step\":\"$STEP\",\"progress\":$PROGRESS,\"details\":\"$DETAILS\",\"server_ip\":\"$(hostname -I | awk '{print $1}')\"}" \
          || true
      fi

  # Admin login test script
  - path: /usr/local/bin/test-nextcloud-login
    permissions: '0755'
    content: |
      #!/bin/bash
      # Test Nextcloud admin login
      ADMIN_USER="admin"
      ADMIN_PASS="${admin_password}"
      
      echo "Testing Nextcloud admin login..."
      
      # Use OCS API to verify admin user
      RESPONSE=$(curl -s -u "$ADMIN_USER:$ADMIN_PASS" \
        "http://localhost/ocs/v2.php/cloud/user" \
        -H "OCS-APIRequest: true" \
        -w "\n%%{http_code}" 2>/dev/null)
      
      HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
      
      if [ "$HTTP_CODE" = "200" ]; then
        echo "Admin login verified successfully!"
        exit 0
      else
        echo "Login test failed with HTTP $HTTP_CODE"
        exit 1
      fi

runcmd:
  - mkdir -p /opt/swiss365
  - mkdir -p /opt/nextcloud
  - mkdir -p /var/log/swiss365
  - touch /var/log/swiss365/install.log
  - swiss365-callback "installing" "init" 5 "Starting Nextcloud installation"
  
  - systemctl enable docker
  - systemctl start docker
  - swiss365-callback "installing" "docker" 15 "Docker started"
  
  # Pull with retry logic
  - swiss365-callback "installing" "pull" 25 "Pulling Docker images (with retry)"
  - |
    cd /opt/nextcloud
    for i in 1 2 3 4 5; do
      echo "Docker-compose pull attempt $i..."
      if docker-compose pull; then
        echo "Pull successful on attempt $i"
        break
      fi
      echo "Pull failed, waiting before retry..."
      sleep $((i * 10))
      if [ $i -eq 5 ]; then
        swiss365-callback "error" "pull" 30 "Failed to pull Docker images after 5 attempts"
        exit 1
      fi
    done
  
  # Start database and redis first
  - swiss365-callback "installing" "database" 35 "Starting database and redis"
  - cd /opt/nextcloud && docker-compose up -d db redis
  
  # Wait for database to be ready with robust check
  - |
    echo "Waiting for MariaDB..."
    for i in {1..60}; do
      # Try multiple methods to check DB readiness
      if docker exec nextcloud-db mysqladmin ping -h localhost -u root -p${db_password} --silent 2>/dev/null; then
        echo "MariaDB is ready (mysqladmin)"
        break
      fi
      # Alternative: direct query test
      if docker exec nextcloud-db mysql -u nextcloud -p${db_password} -e "SELECT 1" nextcloud 2>/dev/null; then
        echo "MariaDB is ready (query test)"
        break
      fi
      echo "Waiting for MariaDB... ($i/60)"
      sleep 5
    done
  - swiss365-callback "installing" "database" 45 "Database ready"
  
  # Now start Nextcloud
  - swiss365-callback "installing" "start" 50 "Starting Nextcloud"
  - cd /opt/nextcloud && docker-compose up -d nextcloud
  
  # Wait for Nextcloud installation to complete
  - swiss365-callback "installing" "healthcheck" 55 "Waiting for Nextcloud installation"
  - |
    echo "Waiting for Nextcloud to initialize..."
    for i in {1..90}; do
      # Check if installation is complete via status.php
      STATUS_RESPONSE=$(curl -s http://localhost/status.php 2>/dev/null)
      if echo "$STATUS_RESPONSE" | grep -q '"installed":true'; then
        echo "Nextcloud installation complete!"
        break
      fi
      
      # Also check HTTP response
      HTTP_CODE=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost/status.php 2>/dev/null || echo "000")
      if [ "$HTTP_CODE" = "200" ]; then
        swiss365-callback "installing" "healthcheck" 65 "Nextcloud status.php responding"
      fi
      
      echo "Waiting for Nextcloud... ($i/90) HTTP: $HTTP_CODE"
      sleep 5
    done
  
  # Verify admin user exists
  - swiss365-callback "installing" "verify-admin" 70 "Verifying admin user"
  - |
    ADMIN_OK=false
    for i in {1..20}; do
      # Test admin login via OCS API
      OCS_RESPONSE=$(curl -s -u "admin:${admin_password}" \
        "http://localhost/ocs/v2.php/cloud/user" \
        -H "OCS-APIRequest: true" \
        -w "\n%%{http_code}" 2>/dev/null)
      
      HTTP_CODE=$(echo "$OCS_RESPONSE" | tail -n1)
      
      if [ "$HTTP_CODE" = "200" ]; then
        echo "Admin user verified successfully!"
        ADMIN_OK=true
        break
      fi
      
      echo "Admin verification attempt $i - HTTP $HTTP_CODE"
      sleep 5
    done
    
    if [ "$ADMIN_OK" = "false" ]; then
      echo "WARNING: Admin verification failed, checking if user exists via occ..."
      docker exec -u www-data nextcloud php occ user:info admin || true
    fi
  
  # Enable user provisioning API
  - swiss365-callback "installing" "config" 80 "Enabling provisioning APIs"
  - docker exec -u www-data nextcloud php occ app:enable provisioning_api || true
  - docker exec -u www-data nextcloud php occ app:enable user_ldap || true
  
  # Configure for multi-tenant
  - docker exec -u www-data nextcloud php occ config:system:set default_quota --value="5 GB" || true
  
  # Start status server
  - swiss365-callback "installing" "status-server" 90 "Starting status server"
  - systemctl daemon-reload
  - systemctl enable swiss365-status
  - systemctl start swiss365-status
  
  # Configure and ACTIVATE firewall
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 8081/tcp
  - ufw allow 9365/tcp
  - ufw --force enable
  
  # Final health verification with login test
  - |
    # Check status.php
    STATUS_CHECK=$(curl -s http://localhost/status.php 2>/dev/null)
    INSTALLED=$(echo "$STATUS_CHECK" | grep -q '"installed":true' && echo "true" || echo "false")
    
    # Check admin login
    ADMIN_CHECK=$(curl -s -o /dev/null -w "%%{http_code}" \
      -u "admin:${admin_password}" \
      "http://localhost/ocs/v2.php/cloud/user" \
      -H "OCS-APIRequest: true" 2>/dev/null)
    
    if [ "$INSTALLED" = "true" ] && [ "$ADMIN_CHECK" = "200" ]; then
      swiss365-callback "ready" "complete" 100 "Nextcloud installation complete - Admin verified"
    elif [ "$INSTALLED" = "true" ]; then
      swiss365-callback "ready" "complete" 100 "Nextcloud installation complete - Status verified"
    else
      HTTP_CODE=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost/status.php 2>/dev/null || echo "000")
      swiss365-callback "error" "healthcheck" 95 "Nextcloud not responding (HTTP $HTTP_CODE, Installed: $INSTALLED)"
    fi
