#cloud-config
# Central Mailcow Server - Multi-Domain Mail

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git
  - curl

runcmd:
  - systemctl enable docker
  - systemctl start docker
  
  # Clone Mailcow
  - cd /opt && git clone https://github.com/mailcow/mailcow-dockerized.git mailcow
  - cd /opt/mailcow
  
  # Generate config
  - |
    cat > /opt/mailcow/mailcow.conf << 'EOF'
    MAILCOW_HOSTNAME=${mailcow_domain}
    DBNAME=mailcow
    DBUSER=mailcow
    DBPASS=${db_password}
    DBROOT=${db_password}
    HTTP_PORT=80
    HTTPS_PORT=443
    HTTP_BIND=0.0.0.0
    HTTPS_BIND=0.0.0.0
    SMTP_PORT=25
    SMTPS_PORT=465
    SUBMISSION_PORT=587
    IMAP_PORT=143
    IMAPS_PORT=993
    POP_PORT=110
    POPS_PORT=995
    SIEVE_PORT=4190
    DOVEADM_PORT=127.0.0.1:19991
    SQL_PORT=127.0.0.1:13306
    SOLR_PORT=127.0.0.1:18983
    REDIS_PORT=127.0.0.1:7654
    TZ=Europe/Zurich
    COMPOSE_PROJECT_NAME=mailcow
    SKIP_LETS_ENCRYPT=y
    SKIP_CLAMD=n
    SKIP_SOGO=n
    ALLOW_ADMIN_EMAIL_LOGIN=y
    ADDITIONAL_SAN=
    API_KEY=
    API_KEY_READ_ONLY=
    API_ALLOW_FROM=0.0.0.0/0
    MAILDIR_GC_TIME=7200
    ACL_ANYONE=disallow
    MAILDIR_SUB=Maildir
    SOGO_EXPIRE_SESSION=480
    LOG_LINES=9999
    WATCHDOG_NOTIFY_EMAIL=
    WATCHDOG_NOTIFY_BAN=y
    WATCHDOG_EXTERNAL_CHECKS=n
    WATCHDOG_MYSQL_REPLICATION_CHECKS=n
    IPV4_NETWORK=172.22.1
    IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
    SNAT_TO_SOURCE=n
    SNAT6_TO_SOURCE=n
    EOF
  
  # Start Mailcow
  - cd /opt/mailcow && docker-compose pull
  - cd /opt/mailcow && docker-compose up -d
  
  # Wait for startup
  - sleep 120
  
  # Set admin password via API
  - |
    docker exec -i $(docker ps -qf "name=mailcow-php-fpm") php -r "
    \$pdo = new PDO('mysql:host=mysql;dbname=mailcow', 'mailcow', '${db_password}');
    \$hash = password_hash('${admin_password}', PASSWORD_BCRYPT);
    \$pdo->exec(\"UPDATE admin SET password='\$hash' WHERE username='admin'\");
    "
