#cloud-config
# Central Keycloak Server - Multi-Realm IAM

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - curl

write_files:
  - path: /opt/keycloak/docker-compose.yml
    permissions: '0644'
    content: |
      version: '3.8'
      
      services:
        postgres:
          image: postgres:15-alpine
          container_name: keycloak-postgres
          restart: always
          environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: ${db_password}
          volumes:
            - postgres-data:/var/lib/postgresql/data
          networks:
            - keycloak-net
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
            interval: 10s
            timeout: 5s
            retries: 5
        
        keycloak:
          image: quay.io/keycloak/keycloak:23.0
          container_name: keycloak
          restart: always
          depends_on:
            postgres:
              condition: service_healthy
          environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: ${db_password}
            KC_HOSTNAME: ${keycloak_domain}
            KC_HOSTNAME_STRICT: false
            KC_HTTP_ENABLED: true
            KC_PROXY: edge
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: ${admin_password}
          command: start
          ports:
            - "80:8080"
          networks:
            - keycloak-net
      
      networks:
        keycloak-net:
          driver: bridge
      
      volumes:
        postgres-data:

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /opt/keycloak
  - cd /opt/keycloak && docker-compose up -d
  
  # Wait for Keycloak to initialize
  - sleep 120
