#cloud-config
# Central Keycloak Server - Multi-Realm IAM with Status Server
# IMPROVED: Docker-pull retry, admin login test, UFW activation

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - curl
  - jq
  - python3

write_files:
  - path: /opt/keycloak/docker-compose.yml
    permissions: '0644'
    content: |
      version: '2.4'
      
      services:
        postgres:
          image: postgres:15-alpine
          container_name: keycloak-postgres
          restart: always
          environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: ${db_password}
          volumes:
            - postgres-data:/var/lib/postgresql/data
          networks:
            - keycloak-net
        
        keycloak:
          image: quay.io/keycloak/keycloak:23.0
          container_name: keycloak
          restart: always
          depends_on:
            - postgres
          environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: ${db_password}
            KC_HOSTNAME: ${keycloak_domain}
            KC_HOSTNAME_STRICT: false
            KC_HTTP_ENABLED: true
            KC_PROXY: edge
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: ${admin_password}
          command: start
          ports:
            - "80:8080"
          networks:
            - keycloak-net
      
      networks:
        keycloak-net:
          driver: bridge
      
      volumes:
        postgres-data:

  - path: /opt/swiss365/status-server.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """Swiss365 Unified Status Server for Keycloak"""
      import http.server
      import json
      import subprocess
      import os
      import hashlib
      import hmac
      import time
      from urllib.parse import urlparse, parse_qs

      STATUS_PORT = 8081
      AGENT_PORT = 9365
      AGENT_SECRET = "${agent_secret}"

      def run_cmd(cmd, timeout=30):
          try:
              result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)
              return result.stdout.strip(), result.returncode
          except Exception as e:
              return str(e), 1

      def get_docker_status():
          containers = []
          output, _ = run_cmd("docker ps -a --format '{{.Names}}|{{.Status}}|{{.Image}}'")
          for line in output.split('\n'):
              if '|' in line:
                  parts = line.split('|')
                  containers.append({
                      'name': parts[0],
                      'status': parts[1],
                      'image': parts[2] if len(parts) > 2 else ''
                  })
          return containers

      def get_system_metrics():
          cpu, _ = run_cmd("top -bn1 | grep 'Cpu(s)' | awk '{print $2}'")
          mem, _ = run_cmd("free -m | awk 'NR==2{printf \"%.1f\", $3*100/$2}'")
          disk, _ = run_cmd("df -h / | awk 'NR==2{print $5}' | tr -d '%'")
          return {'cpu': cpu, 'memory': mem, 'disk': disk}

      def get_keycloak_health():
          # Check Keycloak health endpoint
          status, _ = run_cmd("curl -s -o /dev/null -w '%%{http_code}' http://localhost/health/ready 2>/dev/null || echo '0'")
          # Check critical containers
          keycloak, _ = run_cmd("docker ps -q -f name=keycloak -f status=running")
          postgres, _ = run_cmd("docker ps -q -f name=keycloak-postgres -f status=running")
          return {
              'api_responding': status in ['200', '404'],  # 404 is OK, means KC is running
              'keycloak_running': bool(keycloak),
              'postgres_running': bool(postgres)
          }

      def get_install_logs():
          logs = []
          log_file = '/var/log/swiss365/install.log'
          if os.path.exists(log_file):
              with open(log_file, 'r') as f:
                  logs = f.readlines()[-100:]
          return [l.strip() for l in logs]

      class StatusHandler(http.server.BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              pass

          def send_json(self, data, status=200):
              self.send_response(status)
              self.send_header('Content-Type', 'application/json')
              self.send_header('Access-Control-Allow-Origin', '*')
              self.end_headers()
              self.wfile.write(json.dumps(data).encode())

          def do_GET(self):
              path = urlparse(self.path).path
              
              if path == '/health':
                  self.send_json({'status': 'ok', 'service': 'keycloak'})
              elif path == '/status':
                  health = get_keycloak_health()
                  self.send_json({
                      'service': 'keycloak',
                      'timestamp': time.time(),
                      'healthy': all(health.values()),
                      'health': health,
                      'docker': get_docker_status(),
                      'metrics': get_system_metrics()
                  })
              elif path == '/docker':
                  self.send_json({'containers': get_docker_status()})
              elif path == '/metrics':
                  self.send_json(get_system_metrics())
              elif path == '/logs':
                  self.send_json({'logs': get_install_logs()})
              else:
                  self.send_json({'error': 'Not found'}, 404)

      class AgentHandler(http.server.BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              pass

          def verify_signature(self):
              sig = self.headers.get('X-Signature', '')
              content_length = int(self.headers.get('Content-Length', 0))
              body = self.rfile.read(content_length).decode() if content_length > 0 else ''
              expected = hmac.new(AGENT_SECRET.encode(), body.encode(), hashlib.sha256).hexdigest()
              return hmac.compare_digest(sig, expected), body

          def send_json(self, data, status=200):
              self.send_response(status)
              self.send_header('Content-Type', 'application/json')
              self.send_header('Access-Control-Allow-Origin', '*')
              self.end_headers()
              self.wfile.write(json.dumps(data).encode())

          def do_OPTIONS(self):
              self.send_response(200)
              self.send_header('Access-Control-Allow-Origin', '*')
              self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
              self.send_header('Access-Control-Allow-Headers', 'Content-Type, X-Signature')
              self.end_headers()

          def do_POST(self):
              valid, body = self.verify_signature()
              if not valid:
                  self.send_json({'error': 'Invalid signature'}, 401)
                  return

              path = urlparse(self.path).path
              params = json.loads(body) if body else {}

              if path == '/restart':
                  service = params.get('service', 'all')
                  if service == 'all':
                      output, code = run_cmd('cd /opt/keycloak && docker-compose restart')
                  else:
                      output, code = run_cmd(f'docker restart {service}')
                  self.send_json({'success': code == 0, 'output': output})
              elif path == '/logs':
                  service = params.get('service', '')
                  lines = params.get('lines', 100)
                  if service:
                      output, _ = run_cmd(f'docker logs --tail {lines} {service} 2>&1')
                  else:
                      output, _ = run_cmd(f'tail -n {lines} /var/log/swiss365/install.log')
                  self.send_json({'logs': output})
              elif path == '/execute':
                  cmd = params.get('command', '')
                  if cmd in ['docker-compose up -d', 'docker-compose down', 'docker-compose restart']:
                      output, code = run_cmd(f'cd /opt/keycloak && {cmd}')
                      self.send_json({'success': code == 0, 'output': output})
                  else:
                      self.send_json({'error': 'Command not allowed'}, 403)
              else:
                  self.send_json({'error': 'Not found'}, 404)

      if __name__ == '__main__':
          import threading
          
          status_server = http.server.HTTPServer(('0.0.0.0', STATUS_PORT), StatusHandler)
          status_thread = threading.Thread(target=status_server.serve_forever)
          status_thread.daemon = True
          status_thread.start()
          print(f"Status server running on port {STATUS_PORT}")
          
          agent_server = http.server.HTTPServer(('0.0.0.0', AGENT_PORT), AgentHandler)
          print(f"Agent server running on port {AGENT_PORT}")
          agent_server.serve_forever()

  - path: /etc/systemd/system/swiss365-status.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Swiss365 Status Server
      After=network.target docker.service

      [Service]
      Type=simple
      ExecStart=/usr/bin/python3 /opt/swiss365/status-server.py
      Restart=always
      RestartSec=5
      StandardOutput=append:/var/log/swiss365/status-server.log
      StandardError=append:/var/log/swiss365/status-server.log

      [Install]
      WantedBy=multi-user.target

  - path: /usr/local/bin/swiss365-callback
    permissions: '0755'
    content: |
      #!/bin/bash
      STATUS=$1
      STEP=$2
      PROGRESS=$3
      DETAILS=$4
      
      CALLBACK_URL="${callback_url}"
      WORKSPACE_ID="${workspace_id}"
      SERVER_TYPE="keycloak"
      
      mkdir -p /var/log/swiss365
      echo "$(date '+%Y-%m-%d %H:%M:%S') [$STATUS] $STEP ($PROGRESS%) - $DETAILS" >> /var/log/swiss365/install.log
      
      if [ -n "$CALLBACK_URL" ]; then
        curl -s -X POST "$CALLBACK_URL" \
          -H "Content-Type: application/json" \
          -d "{\"workspace_id\":\"$WORKSPACE_ID\",\"server_type\":\"$SERVER_TYPE\",\"status\":\"$STATUS\",\"current_step\":\"$STEP\",\"progress\":$PROGRESS,\"details\":\"$DETAILS\",\"server_ip\":\"$(hostname -I | awk '{print $1}')\"}" \
          || true
      fi

  # Admin login test script
  - path: /usr/local/bin/test-keycloak-login
    permissions: '0755'
    content: |
      #!/bin/bash
      # Test Keycloak admin login via token endpoint
      ADMIN_USER="admin"
      ADMIN_PASS="${admin_password}"
      
      echo "Testing Keycloak admin login..."
      
      # Get admin token
      RESPONSE=$(curl -s -X POST \
        "http://localhost/realms/master/protocol/openid-connect/token" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=password" \
        -d "client_id=admin-cli" \
        -d "username=$ADMIN_USER" \
        -d "password=$ADMIN_PASS" \
        -w "\n%%{http_code}" 2>/dev/null)
      
      HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
      BODY=$(echo "$RESPONSE" | sed '$d')
      
      if [ "$HTTP_CODE" = "200" ] && echo "$BODY" | grep -q "access_token"; then
        echo "Admin login verified successfully!"
        exit 0
      else
        echo "Login test failed with HTTP $HTTP_CODE"
        exit 1
      fi

runcmd:
  - mkdir -p /opt/swiss365
  - mkdir -p /opt/keycloak
  - mkdir -p /var/log/swiss365
  - touch /var/log/swiss365/install.log
  - swiss365-callback "installing" "init" 5 "Starting Keycloak installation"
  
  - systemctl enable docker
  - systemctl start docker
  - swiss365-callback "installing" "docker" 15 "Docker started"
  
  # Pull with retry logic
  - swiss365-callback "installing" "pull" 25 "Pulling Docker images (with retry)"
  - |
    cd /opt/keycloak
    for i in 1 2 3 4 5; do
      echo "Docker-compose pull attempt $i..."
      if docker-compose pull; then
        echo "Pull successful on attempt $i"
        break
      fi
      echo "Pull failed, waiting before retry..."
      sleep $((i * 10))
      if [ $i -eq 5 ]; then
        swiss365-callback "error" "pull" 30 "Failed to pull Docker images after 5 attempts"
        exit 1
      fi
    done
  
  # Start PostgreSQL first and wait for it
  - swiss365-callback "installing" "database" 35 "Starting PostgreSQL"
  - cd /opt/keycloak && docker-compose up -d postgres
  
  # Wait for PostgreSQL to be healthy with robust check
  - |
    echo "Waiting for PostgreSQL..."
    for i in {1..60}; do
      if docker exec keycloak-postgres pg_isready -U keycloak -d keycloak >/dev/null 2>&1; then
        # Double-check with actual query
        if docker exec keycloak-postgres psql -U keycloak -d keycloak -c "SELECT 1" >/dev/null 2>&1; then
          echo "PostgreSQL is ready"
          break
        fi
      fi
      echo "Waiting for PostgreSQL... ($i/60)"
      sleep 5
    done
  - swiss365-callback "installing" "database" 45 "PostgreSQL ready"
  
  # Now start Keycloak
  - swiss365-callback "installing" "start" 50 "Starting Keycloak"
  - cd /opt/keycloak && docker-compose up -d keycloak
  
  # Wait for Keycloak to be ready (it takes longer to initialize)
  - swiss365-callback "installing" "healthcheck" 55 "Waiting for Keycloak to be ready"
  - |
    echo "Waiting for Keycloak to initialize..."
    for i in {1..90}; do
      # Check health endpoint first
      HEALTH_CODE=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost/health/ready 2>/dev/null || echo "000")
      
      if [ "$HEALTH_CODE" = "200" ]; then
        swiss365-callback "installing" "healthcheck" 70 "Keycloak health endpoint responding"
        break
      fi
      
      # Fallback: check main page
      HTTP_CODE=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost/ 2>/dev/null || echo "000")
      if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "302" ] || [ "$HTTP_CODE" = "303" ]; then
        swiss365-callback "installing" "healthcheck" 70 "Keycloak web responding (HTTP $HTTP_CODE)"
        break
      fi
      
      echo "Waiting for Keycloak... ($i/90) Health: $HEALTH_CODE, Web: $HTTP_CODE"
      sleep 5
    done
  
  # Test admin login
  - swiss365-callback "installing" "login-test" 75 "Testing admin login"
  - |
    LOGIN_OK=false
    for i in {1..30}; do
      # Test admin token endpoint
      TOKEN_RESPONSE=$(curl -s -X POST \
        "http://localhost/realms/master/protocol/openid-connect/token" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=password" \
        -d "client_id=admin-cli" \
        -d "username=admin" \
        -d "password=${admin_password}" \
        -w "\n%%{http_code}" 2>/dev/null)
      
      HTTP_CODE=$(echo "$TOKEN_RESPONSE" | tail -n1)
      BODY=$(echo "$TOKEN_RESPONSE" | sed '$d')
      
      if [ "$HTTP_CODE" = "200" ] && echo "$BODY" | grep -q "access_token"; then
        echo "Admin login verified successfully!"
        LOGIN_OK=true
        break
      fi
      
      echo "Admin login test attempt $i - HTTP $HTTP_CODE"
      sleep 5
    done
    
    if [ "$LOGIN_OK" = "true" ]; then
      swiss365-callback "installing" "login-test" 85 "Admin login verified"
    else
      echo "WARNING: Admin login test failed, but continuing..."
    fi
  
  # Start status server
  - swiss365-callback "installing" "status-server" 90 "Starting status server"
  - systemctl daemon-reload
  - systemctl enable swiss365-status
  - systemctl start swiss365-status
  
  # Configure and ACTIVATE firewall
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 8081/tcp
  - ufw allow 9365/tcp
  - ufw --force enable
  
  # Final health verification with login test
  - |
    # Test admin login
    FINAL_TOKEN=$(curl -s -X POST \
      "http://localhost/realms/master/protocol/openid-connect/token" \
      -H "Content-Type: application/x-www-form-urlencoded" \
      -d "grant_type=password" \
      -d "client_id=admin-cli" \
      -d "username=admin" \
      -d "password=${admin_password}" 2>/dev/null)
    
    if echo "$FINAL_TOKEN" | grep -q "access_token"; then
      swiss365-callback "ready" "complete" 100 "Keycloak installation complete - Admin login verified"
    else
      # Fallback: check if web is responding
      WEB_CODE=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost/ 2>/dev/null || echo "000")
      if [ "$WEB_CODE" = "200" ] || [ "$WEB_CODE" = "302" ] || [ "$WEB_CODE" = "303" ]; then
        swiss365-callback "ready" "complete" 100 "Keycloak installation complete - Web verified"
      else
        swiss365-callback "error" "healthcheck" 95 "Keycloak not responding (HTTP $WEB_CODE)"
      fi
    fi
