#cloud-config
# Control Node cloud-init - Installs Docker and Guacamole stack

packages:
  - htop
  - curl
  - gnupg
  - lsb-release

ssh_pwauth: true
chpasswd:
  list: |
    root:${root_password}
  expire: False

write_files:
  - path: /opt/guacamole/docker-compose.yml
    content: |
      version: '3.8'
      services:
        guacd:
          image: guacamole/guacd:latest
          container_name: guacd
          restart: always
          networks:
            - guacamole_net

        postgres:
          image: postgres:15
          container_name: guac_postgres
          restart: always
          environment:
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
            POSTGRES_DB: guacamole
          volumes:
            - postgres_data:/var/lib/postgresql/data
            - /opt/guacamole/initdb:/docker-entrypoint-initdb.d
          networks:
            - guacamole_net
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U guacamole -d guacamole"]
            interval: 10s
            timeout: 5s
            retries: 5

        guacamole:
          image: guacamole/guacamole:latest
          container_name: guacamole
          restart: always
          ports:
            - "8080:8080"
          environment:
            GUACD_HOSTNAME: guacd
            POSTGRES_HOSTNAME: postgres
            POSTGRES_DATABASE: guacamole
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
          depends_on:
            postgres:
              condition: service_healthy
            guacd:
              condition: service_started
          networks:
            - guacamole_net

      networks:
        guacamole_net:
          driver: bridge

      volumes:
        postgres_data:

  - path: /opt/guacamole/setup-connections.sql
    content: |
      -- Add RDP connections for Workspace and Desktop servers
      -- This runs after the main schema is initialized
      
      -- Only add connections if IPs are provided
      DO $$
      BEGIN
        -- Add Workspace connection if IP is provided
        IF '${workspace_ip}' != '' THEN
          INSERT INTO guacamole_connection (connection_name, protocol)
          VALUES ('Workspace', 'rdp')
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'hostname', '${workspace_ip}'
          FROM guacamole_connection WHERE connection_name = 'Workspace'
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'port', '3389'
          FROM guacamole_connection WHERE connection_name = 'Workspace'
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'username', 'root'
          FROM guacamole_connection WHERE connection_name = 'Workspace'
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'password', '${workspace_password}'
          FROM guacamole_connection WHERE connection_name = 'Workspace'
          ON CONFLICT DO NOTHING;
          
          -- Grant access to guacadmin
          INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
          SELECT entity_id, connection_id, 'READ'
          FROM guacamole_entity, guacamole_connection
          WHERE guacamole_entity.name = 'guacadmin' AND guacamole_connection.connection_name = 'Workspace'
          ON CONFLICT DO NOTHING;
        END IF;
        
        -- Add Desktop connection if IP is provided
        IF '${desktop_ip}' != '' THEN
          INSERT INTO guacamole_connection (connection_name, protocol)
          VALUES ('Desktop', 'rdp')
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'hostname', '${desktop_ip}'
          FROM guacamole_connection WHERE connection_name = 'Desktop'
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'port', '3389'
          FROM guacamole_connection WHERE connection_name = 'Desktop'
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'username', 'root'
          FROM guacamole_connection WHERE connection_name = 'Desktop'
          ON CONFLICT DO NOTHING;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
          SELECT connection_id, 'password', '${desktop_password}'
          FROM guacamole_connection WHERE connection_name = 'Desktop'
          ON CONFLICT DO NOTHING;
          
          -- Grant access to guacadmin
          INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
          SELECT entity_id, connection_id, 'READ'
          FROM guacamole_entity, guacamole_connection
          WHERE guacamole_entity.name = 'guacadmin' AND guacamole_connection.connection_name = 'Desktop'
          ON CONFLICT DO NOTHING;
        END IF;
      END $$;

  - path: /opt/guacamole/install.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      
      echo "$(date): Starting Guacamole installation..."
      
      # Install Docker
      curl -fsSL https://get.docker.com | sh
      
      # Install Docker Compose
      apt-get update && apt-get install -y docker-compose-plugin
      
      # Create initdb directory
      mkdir -p /opt/guacamole/initdb
      
      # Pull images first
      echo "$(date): Pulling Docker images..."
      docker pull guacamole/guacd:latest
      docker pull guacamole/guacamole:latest
      docker pull postgres:15
      
      # Generate database schema
      echo "$(date): Generating database schema..."
      docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > /opt/guacamole/initdb/01-schema.sql
      
      # Copy connection setup script
      cp /opt/guacamole/setup-connections.sql /opt/guacamole/initdb/02-connections.sql
      
      # Start the stack
      echo "$(date): Starting Guacamole stack..."
      cd /opt/guacamole
      docker compose up -d
      
      # Wait for PostgreSQL to be ready
      echo "$(date): Waiting for PostgreSQL..."
      for i in {1..30}; do
        if docker exec guac_postgres pg_isready -U guacamole -d guacamole > /dev/null 2>&1; then
          echo "$(date): PostgreSQL is ready!"
          break
        fi
        sleep 2
      done
      
      # Wait for Guacamole to be ready
      echo "$(date): Waiting for Guacamole..."
      for i in {1..30}; do
        if curl -s http://localhost:8080/guacamole/ > /dev/null 2>&1; then
          echo "$(date): Guacamole is ready!"
          break
        fi
        sleep 2
      done
      
      # Verify installation
      echo "$(date): Verifying installation..."
      docker ps
      
      # Restart guacamole to ensure connections are loaded
      docker restart guacamole
      sleep 5
      
      echo "$(date): Guacamole installation completed!"
      echo "Access Guacamole at: http://$(hostname -I | awk '{print $1}'):8080/guacamole/"
      echo "Default credentials: guacadmin / guacadmin"

runcmd:
  - mkdir -p /opt/guacamole
  - chmod +x /opt/guacamole/install.sh
  - /opt/guacamole/install.sh >> /var/log/guacamole-install.log 2>&1
