#cloud-config
# Control Node Cloud-Init - Installs Docker and deploys Guacamole

packages:
  - htop
  - curl
  - gnupg
  - lsb-release
  - xrdp
  - xfce4
  - xfce4-goodies

ssh_pwauth: true
chpasswd:
  list: |
    root:${root_password_hash}
  expire: False
  encrypted: true

write_files:
  - path: /opt/guacamole/docker-compose.yml
    permissions: '0644'
    content: |
      version: '3.8'
      services:
        guacd:
          image: guacamole/guacd:latest
          container_name: guacd
          restart: always
          networks:
            - guacamole_net

        postgres:
          image: postgres:15
          container_name: guacamole_db
          restart: always
          environment:
            POSTGRES_DB: guacamole_db
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
          volumes:
            - postgres_data:/var/lib/postgresql/data
            - /opt/guacamole/initdb:/docker-entrypoint-initdb.d:ro
          networks:
            - guacamole_net
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U guacamole -d guacamole_db"]
            interval: 5s
            timeout: 5s
            retries: 10

        guacamole:
          image: guacamole/guacamole:latest
          container_name: guacamole
          restart: always
          depends_on:
            postgres:
              condition: service_healthy
            guacd:
              condition: service_started
          environment:
            GUACD_HOSTNAME: guacd
            POSTGRES_HOSTNAME: postgres
            POSTGRES_DATABASE: guacamole_db
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
          ports:
            - "8080:8080"
          networks:
            - guacamole_net

      networks:
        guacamole_net:
          driver: bridge

      volumes:
        postgres_data:

  - path: /opt/guacamole/setup-connections.sql
    permissions: '0644'
    content: |
      -- Add RDP connections after database is initialized
      -- This runs as 02-connections.sql after schema initialization
      
      DO $$
      DECLARE
        workspace_conn_id integer;
        desktop_conn_id integer;
        admin_entity_id integer;
      BEGIN
        -- Get the entity_id for guacadmin user
        SELECT entity_id INTO admin_entity_id 
        FROM guacamole_user 
        WHERE username = 'guacadmin';
        
        IF admin_entity_id IS NULL THEN
          RAISE NOTICE 'guacadmin user not found, skipping connection setup';
          RETURN;
        END IF;
        
        %{ if workspace_ip != "" }
        -- Create Workspace connection
        IF NOT EXISTS (SELECT 1 FROM guacamole_connection WHERE connection_name = 'Workspace') THEN
          INSERT INTO guacamole_connection (connection_name, protocol) 
          VALUES ('Workspace', 'rdp')
          RETURNING connection_id INTO workspace_conn_id;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value) VALUES
            (workspace_conn_id, 'hostname', '${workspace_ip}'),
            (workspace_conn_id, 'port', '3389'),
            (workspace_conn_id, 'username', 'root'),
            (workspace_conn_id, 'password', '${workspace_password}'),
            (workspace_conn_id, 'ignore-cert', 'true'),
            (workspace_conn_id, 'security', 'any');
          
          INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
          VALUES (admin_entity_id, workspace_conn_id, 'READ');
          
          RAISE NOTICE 'Workspace connection created with ID %', workspace_conn_id;
        END IF;
        %{ endif }
        
        %{ if desktop_ip != "" }
        -- Create Desktop connection
        IF NOT EXISTS (SELECT 1 FROM guacamole_connection WHERE connection_name = 'Desktop') THEN
          INSERT INTO guacamole_connection (connection_name, protocol) 
          VALUES ('Desktop', 'rdp')
          RETURNING connection_id INTO desktop_conn_id;
          
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value) VALUES
            (desktop_conn_id, 'hostname', '${desktop_ip}'),
            (desktop_conn_id, 'port', '3389'),
            (desktop_conn_id, 'username', 'root'),
            (desktop_conn_id, 'password', '${desktop_password}'),
            (desktop_conn_id, 'ignore-cert', 'true'),
            (desktop_conn_id, 'security', 'any');
          
          INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
          VALUES (admin_entity_id, desktop_conn_id, 'READ');
          
          RAISE NOTICE 'Desktop connection created with ID %', desktop_conn_id;
        END IF;
        %{ endif }
        
      END $$;

  - path: /opt/guacamole/install.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      exec > /var/log/guacamole-setup.log 2>&1
      echo "$(date): Starting Guacamole installation..."

      # Install Docker
      echo "$(date): Installing Docker..."
      curl -fsSL https://get.docker.com | sh
      systemctl enable docker
      systemctl start docker

      # Wait for Docker to be ready
      echo "$(date): Waiting for Docker..."
      sleep 10
      docker info

      # Create initdb directory
      mkdir -p /opt/guacamole/initdb

      # Generate Guacamole database schema FIRST (before starting containers)
      echo "$(date): Generating Guacamole database schema..."
      docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > /opt/guacamole/initdb/01-schema.sql

      # Verify schema was generated
      if [ ! -s /opt/guacamole/initdb/01-schema.sql ]; then
        echo "$(date): ERROR: Failed to generate database schema!"
        exit 1
      fi
      
      SCHEMA_LINES=$(wc -l < /opt/guacamole/initdb/01-schema.sql)
      echo "$(date): Schema generated successfully, $SCHEMA_LINES lines"

      # Copy connection setup SQL (runs after schema as 02-connections.sql)
      cp /opt/guacamole/setup-connections.sql /opt/guacamole/initdb/02-connections.sql
      echo "$(date): Connection setup SQL copied"

      # List initdb contents
      echo "$(date): InitDB directory contents:"
      ls -la /opt/guacamole/initdb/

      # Now start the Guacamole stack
      echo "$(date): Starting Guacamole containers..."
      cd /opt/guacamole
      docker compose up -d

      # Wait for PostgreSQL to initialize and be healthy
      echo "$(date): Waiting for PostgreSQL to be ready..."
      for i in {1..60}; do
        if docker exec guacamole_db pg_isready -U guacamole -d guacamole_db 2>/dev/null; then
          echo "$(date): PostgreSQL is ready!"
          break
        fi
        echo "$(date): Waiting for PostgreSQL... ($i/60)"
        sleep 2
      done

      # Wait a bit more for init scripts to complete
      sleep 10

      # Verify database tables exist
      echo "$(date): Verifying database tables..."
      docker exec guacamole_db psql -U guacamole -d guacamole_db -c '\dt' || echo "Warning: Could not list tables"

      # Check if guacadmin user exists
      echo "$(date): Checking for guacadmin user..."
      docker exec guacamole_db psql -U guacamole -d guacamole_db -c "SELECT username FROM guacamole_user;" || echo "Warning: Could not query users"

      # Wait for Guacamole web to be ready
      echo "$(date): Waiting for Guacamole web interface..."
      for i in {1..30}; do
        if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/guacamole/ | grep -q "200\|302"; then
          echo "$(date): Guacamole web interface is responding!"
          break
        fi
        echo "$(date): Waiting for Guacamole web... ($i/30)"
        sleep 3
      done

      # Final status
      echo "$(date): Container status:"
      docker ps -a

      echo "$(date): Guacamole installation completed!"
      echo "$(date): Access Guacamole at http://$(hostname -I | awk '{print $1}'):8080/guacamole"
      echo "$(date): Default credentials: guacadmin / guacadmin"

runcmd:
  - mkdir -p /opt/guacamole
  - chmod +x /opt/guacamole/install.sh
  - /opt/guacamole/install.sh
