#cloud-config
# Control Node - Guacamole Gateway for Swiss365 Linux Hosting Platform
# Exposes status via HTTP on port 8081 for remote monitoring

packages:
  - htop
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - python3
  - jq

# Enable SSH password authentication
ssh_pwauth: true

# Set root password (plaintext - Terraform passes plaintext password)
chpasswd:
  list: |
    root:${root_password}
  expire: False

runcmd:
  # Configure SSH for password authentication and root login
  - sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - |
    for f in /etc/ssh/sshd_config.d/*.conf; do
      if [ -f "$f" ]; then
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' "$f"
        sed -i 's/^PermitRootLogin no/PermitRootLogin yes/' "$f"
        sed -i 's/^PermitRootLogin prohibit-password/PermitRootLogin yes/' "$f"
      fi
    done
  - systemctl restart ssh
  
  # Initialize logging system
  - mkdir -p /var/log/swiss365
  - chmod 755 /var/log/swiss365
  - echo '{"status":"initializing","step":"boot","progress":0,"server_role":"control_node","timestamp":"'$(date -Iseconds)'","logs":[]}' > /var/log/swiss365/status.json
  
  # Start HTTP status server (port 8081)
  - chmod +x /opt/swiss365/status-server.py
  - nohup python3 /opt/swiss365/status-server.py > /var/log/swiss365/status-server.log 2>&1 &
  
  # Create Guacamole directory
  - mkdir -p /opt/guacamole
  - chmod +x /opt/guacamole/install.sh
  
  # Start Guacamole installation
  - /opt/guacamole/install.sh

write_files:
  # Swiss365 Status HTTP Server - Exposes logs via HTTP API
  - path: /opt/swiss365/status-server.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """Swiss365 Status Server - HTTP API for installation status and logs"""
      import http.server
      import json
      import os
      import subprocess
      from datetime import datetime
      
      STATUS_FILE = "/var/log/swiss365/status.json"
      LOG_FILE = "/var/log/swiss365/install.log"
      PORT = 8081
      
      class StatusHandler(http.server.BaseHTTPRequestHandler):
          def do_GET(self):
              # CORS headers for Edge Function access
              self.send_response(200)
              self.send_header('Content-type', 'application/json')
              self.send_header('Access-Control-Allow-Origin', '*')
              self.end_headers()
              
              response = {
                  "server_role": "control_node",
                  "timestamp": datetime.now().isoformat(),
                  "status": "unknown",
                  "step": "",
                  "progress": 0,
                  "logs": [],
                  "docker": {},
                  "system": {}
              }
              
              # Read current status
              try:
                  if os.path.exists(STATUS_FILE):
                      with open(STATUS_FILE, 'r') as f:
                          status_data = json.load(f)
                          response.update(status_data)
              except Exception as e:
                  response["error"] = str(e)
              
              # Read last 100 log lines
              try:
                  if os.path.exists(LOG_FILE):
                      with open(LOG_FILE, 'r') as f:
                          lines = f.readlines()
                          response["logs"] = [l.strip() for l in lines[-100:]]
              except Exception as e:
                  response["log_error"] = str(e)
              
              # Get Docker container status
              try:
                  result = subprocess.run(
                      ["docker", "ps", "-a", "--format", "{{.Names}}|{{.Status}}|{{.Ports}}"],
                      capture_output=True, text=True, timeout=5
                  )
                  containers = {}
                  for line in result.stdout.strip().split('\n'):
                      if '|' in line:
                          parts = line.split('|')
                          containers[parts[0]] = {"status": parts[1], "ports": parts[2] if len(parts) > 2 else ""}
                  response["docker"] = containers
              except Exception as e:
                  response["docker_error"] = str(e)
              
              # Get system info
              try:
                  response["system"] = {
                      "hostname": subprocess.run(["hostname"], capture_output=True, text=True).stdout.strip(),
                      "uptime": subprocess.run(["uptime", "-p"], capture_output=True, text=True).stdout.strip(),
                      "memory": subprocess.run(["free", "-h", "--si"], capture_output=True, text=True).stdout.strip().split('\n')[1] if subprocess.run(["free", "-h"], capture_output=True).returncode == 0 else ""
                  }
              except:
                  pass
              
              self.wfile.write(json.dumps(response, indent=2).encode())
          
          def do_OPTIONS(self):
              self.send_response(200)
              self.send_header('Access-Control-Allow-Origin', '*')
              self.send_header('Access-Control-Allow-Methods', 'GET, OPTIONS')
              self.end_headers()
          
          def log_message(self, format, *args):
              pass  # Suppress default logging
      
      if __name__ == "__main__":
          print(f"Starting Swiss365 Status Server on port {PORT}")
          server = http.server.HTTPServer(('0.0.0.0', PORT), StatusHandler)
          server.serve_forever()

  # Status update helper script
  - path: /usr/local/bin/swiss365-status
    permissions: '0755'
    content: |
      #!/bin/bash
      # Usage: swiss365-status <status> <step> <progress> [details]
      STATUS="$1"
      STEP="$2"
      PROGRESS="$3"
      DETAILS="$4"
      
      STATUS_FILE="/var/log/swiss365/status.json"
      LOG_FILE="/var/log/swiss365/install.log"
      
      # Update status JSON
      jq -n \
        --arg status "$STATUS" \
        --arg step "$STEP" \
        --argjson progress "$PROGRESS" \
        --arg details "$DETAILS" \
        --arg timestamp "$(date -Iseconds)" \
        --arg role "control_node" \
        '{status: $status, step: $step, progress: $progress, details: $details, timestamp: $timestamp, server_role: $role}' \
        > "$STATUS_FILE"
      
      # Append to log
      echo "$(date -Iseconds) [$STATUS] $STEP ($PROGRESS%) - $DETAILS" >> "$LOG_FILE"
      
      # Send webhook callback to Supabase Edge Function
      SERVER_IP=$(hostname -I | awk '{print $1}')
      curl -s -X POST "https://zelbakpcnbdkygzvxtrj.supabase.co/functions/v1/installation-callback" \
        -H "Content-Type: application/json" \
        -d "{\"server_ip\":\"$SERVER_IP\",\"server_type\":\"control_node\",\"status\":\"$STATUS\",\"step\":\"$STEP\",\"progress\":$PROGRESS,\"details\":\"$DETAILS\"}" \
        2>/dev/null || true

  # Guacamole Docker Compose
  - path: /opt/guacamole/docker-compose.yml
    permissions: '0644'
    content: |
      services:
        guacd:
          image: guacamole/guacd:latest
          container_name: guacd
          restart: always
          networks:
            - guacamole_net
        
        postgres:
          image: postgres:15
          container_name: guacamole_db
          restart: always
          environment:
            POSTGRES_DB: guacamole
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
          volumes:
            - postgres_data:/var/lib/postgresql/data
            - /opt/guacamole/initdb:/docker-entrypoint-initdb.d:ro
          networks:
            - guacamole_net
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U guacamole -d guacamole"]
            interval: 5s
            timeout: 5s
            retries: 30
            start_period: 30s
        
        guacamole:
          image: guacamole/guacamole:latest
          container_name: guacamole
          restart: always
          ports:
            - "8080:8080"
          environment:
            GUACD_HOSTNAME: guacd
            POSTGRES_HOSTNAME: postgres
            POSTGRES_DATABASE: guacamole
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
          depends_on:
            postgres:
              condition: service_healthy
            guacd:
              condition: service_started
          networks:
            - guacamole_net
      
      networks:
        guacamole_net:
          driver: bridge
      
      volumes:
        postgres_data:

  # RDP Connection Setup SQL
  - path: /opt/guacamole/setup-connections.sql
    permissions: '0644'
    content: |
      -- Swiss365 RDP Connections Setup
      DO $$
      DECLARE
        admin_entity_id integer;
      BEGIN
        SELECT entity_id INTO admin_entity_id FROM guacamole_user WHERE username = 'guacadmin';
        
        %{ if workspace_ip != "" }
        IF NOT EXISTS (SELECT 1 FROM guacamole_connection WHERE connection_name = 'Workspace Server') THEN
          INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('Workspace Server', 'rdp');
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'hostname', '${workspace_ip}' FROM guacamole_connection WHERE connection_name = 'Workspace Server';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'port', '3389' FROM guacamole_connection WHERE connection_name = 'Workspace Server';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'username', 'root' FROM guacamole_connection WHERE connection_name = 'Workspace Server';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'password', '${workspace_password}' FROM guacamole_connection WHERE connection_name = 'Workspace Server';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'ignore-cert', 'true' FROM guacamole_connection WHERE connection_name = 'Workspace Server';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'security', 'any' FROM guacamole_connection WHERE connection_name = 'Workspace Server';
          INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
            SELECT admin_entity_id, connection_id, 'READ' FROM guacamole_connection WHERE connection_name = 'Workspace Server';
        END IF;
        %{ endif }
        
        %{ if desktop_ip != "" }
        IF NOT EXISTS (SELECT 1 FROM guacamole_connection WHERE connection_name = 'Desktop Pool') THEN
          INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('Desktop Pool', 'rdp');
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'hostname', '${desktop_ip}' FROM guacamole_connection WHERE connection_name = 'Desktop Pool';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'port', '3389' FROM guacamole_connection WHERE connection_name = 'Desktop Pool';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'username', 'root' FROM guacamole_connection WHERE connection_name = 'Desktop Pool';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'password', '${desktop_password}' FROM guacamole_connection WHERE connection_name = 'Desktop Pool';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'ignore-cert', 'true' FROM guacamole_connection WHERE connection_name = 'Desktop Pool';
          INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
            SELECT connection_id, 'security', 'any' FROM guacamole_connection WHERE connection_name = 'Desktop Pool';
          INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
            SELECT admin_entity_id, connection_id, 'READ' FROM guacamole_connection WHERE connection_name = 'Desktop Pool';
        END IF;
        %{ endif }
      END $$;

  # Guacamole Installation Script with detailed logging
  - path: /opt/guacamole/install.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      
      LOG_FILE="/var/log/swiss365/install.log"
      exec > >(tee -a $LOG_FILE) 2>&1
      
      echo "=========================================="
      echo "$(date): Swiss365 Control Node Installation"
      echo "=========================================="
      
      swiss365-status "installing" "docker" 10 "Installing Docker Engine"
      
      # Install Docker
      echo "$(date): Installing Docker..."
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      systemctl enable docker
      systemctl start docker
      
      echo "$(date): Docker installed: $(docker --version)"
      swiss365-status "installing" "docker" 20 "Docker installed successfully"
      
      # Wait for Docker
      echo "$(date): Waiting for Docker daemon..."
      for i in {1..30}; do
        if docker info > /dev/null 2>&1; then
          echo "$(date): Docker is ready!"
          break
        fi
        sleep 2
      done
      
      # Generate Guacamole schema
      mkdir -p /opt/guacamole/initdb
      swiss365-status "installing" "schema" 30 "Generating database schema"
      
      echo "$(date): Pulling Guacamole image and generating schema..."
      docker pull guacamole/guacamole:latest
      docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > /opt/guacamole/initdb/01-schema.sql
      
      if [ ! -s /opt/guacamole/initdb/01-schema.sql ]; then
        echo "$(date): ERROR - Schema file is empty!"
        swiss365-status "error" "schema" 30 "Schema generation failed"
        exit 1
      fi
      
      echo "$(date): Schema generated ($(wc -l < /opt/guacamole/initdb/01-schema.sql) lines)"
      swiss365-status "installing" "schema" 40 "Schema generated"
      
      # Copy connection setup
      cp /opt/guacamole/setup-connections.sql /opt/guacamole/initdb/02-connections.sql
      
      # Pull remaining images
      echo "$(date): Pulling Docker images..."
      swiss365-status "installing" "images" 50 "Pulling Docker images"
      docker pull guacamole/guacd:latest
      docker pull postgres:15
      
      # Start containers
      echo "$(date): Starting Guacamole stack..."
      swiss365-status "installing" "containers" 60 "Starting containers"
      cd /opt/guacamole
      docker compose up -d
      
      # Wait for PostgreSQL
      echo "$(date): Waiting for PostgreSQL..."
      swiss365-status "installing" "postgres" 70 "Waiting for PostgreSQL"
      for i in {1..60}; do
        if docker exec guacamole_db pg_isready -U guacamole -d guacamole 2>/dev/null; then
          echo "$(date): PostgreSQL is ready!"
          break
        fi
        sleep 3
      done
      
      sleep 10  # Wait for init scripts
      
      # Verify database
      swiss365-status "installing" "verify" 80 "Verifying database"
      TABLES=$(docker exec guacamole_db psql -U guacamole -d guacamole -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public';" 2>/dev/null | tr -d ' ')
      echo "$(date): Found $TABLES tables"
      
      if [ "$TABLES" -lt 10 ]; then
        echo "$(date): Applying schema manually..."
        docker exec -i guacamole_db psql -U guacamole -d guacamole < /opt/guacamole/initdb/01-schema.sql || true
        sleep 5
      fi
      
      # Restart Guacamole
      docker restart guacamole
      sleep 5
      
      # Wait for web interface
      swiss365-status "installing" "web" 90 "Waiting for web interface"
      for i in {1..30}; do
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/guacamole/ 2>/dev/null || echo "000")
        if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "302" ]; then
          echo "$(date): Guacamole responding (HTTP $HTTP_CODE)"
          break
        fi
        sleep 5
      done
      
      # Test login
      swiss365-status "installing" "login" 95 "Testing login"
      LOGIN_RESULT=$(curl -s -X POST http://localhost:8080/guacamole/api/tokens -d "username=guacadmin&password=guacadmin" 2>/dev/null || echo "failed")
      
      if echo "$LOGIN_RESULT" | grep -q "authToken"; then
        echo "$(date): ✅ Guacamole login successful!"
        swiss365-status "ready" "complete" 100 "Installation complete - Guacamole ready"
      else
        echo "$(date): ⚠️ Login test failed: $LOGIN_RESULT"
        swiss365-status "warning" "login-issue" 95 "Guacamole running but login test failed"
      fi
      
      # Final status
      echo "$(date): Container status:"
      docker ps -a
      
      echo "=========================================="
      echo "$(date): Installation completed!"
      echo "=========================================="
