#cloud-config
# Control Node Cloud-Init - Installs Docker and deploys Guacamole

packages:
  - htop
  - curl
  - gnupg
  - lsb-release
  - xrdp
  - xfce4
  - xfce4-goodies

ssh_pwauth: true
chpasswd:
  list: |
    root:${root_password_hash}
  expire: False
  encrypted: true

write_files:
  - path: /opt/guacamole/docker-compose.yml
    content: |
      version: '3.8'
      services:
        guacd:
          image: guacamole/guacd:latest
          container_name: guacd
          restart: always
          networks:
            - guacamole_net

        postgres:
          image: postgres:15
          container_name: guacamole_db
          restart: always
          environment:
            POSTGRES_DB: guacamole_db
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
          volumes:
            - postgres_data:/var/lib/postgresql/data
            - /opt/guacamole/initdb:/docker-entrypoint-initdb.d:ro
          networks:
            - guacamole_net
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U guacamole -d guacamole_db"]
            interval: 5s
            timeout: 5s
            retries: 10

        guacamole:
          image: guacamole/guacamole:latest
          container_name: guacamole
          restart: always
          depends_on:
            postgres:
              condition: service_healthy
            guacd:
              condition: service_started
          environment:
            GUACD_HOSTNAME: guacd
            POSTGRES_HOSTNAME: postgres
            POSTGRES_DATABASE: guacamole_db
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: ${guac_db_password}
          ports:
            - "8080:8080"
          networks:
            - guacamole_net

      networks:
        guacamole_net:
          driver: bridge

      volumes:
        postgres_data:

  - path: /opt/guacamole/setup-connections.sql
    content: |
      -- Add RDP connections after database is initialized
      -- Workspace Server
      %{ if workspace_ip != "" }
      INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('Workspace', 'rdp');
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'hostname', '${workspace_ip}' FROM guacamole_connection WHERE connection_name = 'Workspace';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'port', '3389' FROM guacamole_connection WHERE connection_name = 'Workspace';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'username', 'root' FROM guacamole_connection WHERE connection_name = 'Workspace';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'password', '${workspace_password}' FROM guacamole_connection WHERE connection_name = 'Workspace';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'ignore-cert', 'true' FROM guacamole_connection WHERE connection_name = 'Workspace';
      INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
      SELECT entity_id, connection_id, 'READ' FROM guacamole_entity, guacamole_connection
      WHERE guacamole_entity.name = 'guacadmin' AND guacamole_connection.connection_name = 'Workspace';
      %{ endif }

      -- Desktop Pool Server
      %{ if desktop_ip != "" }
      INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('Desktop', 'rdp');
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'hostname', '${desktop_ip}' FROM guacamole_connection WHERE connection_name = 'Desktop';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'port', '3389' FROM guacamole_connection WHERE connection_name = 'Desktop';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'username', 'root' FROM guacamole_connection WHERE connection_name = 'Desktop';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'password', '${desktop_password}' FROM guacamole_connection WHERE connection_name = 'Desktop';
      INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
      SELECT connection_id, 'ignore-cert', 'true' FROM guacamole_connection WHERE connection_name = 'Desktop';
      INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
      SELECT entity_id, connection_id, 'READ' FROM guacamole_entity, guacamole_connection
      WHERE guacamole_entity.name = 'guacadmin' AND guacamole_connection.connection_name = 'Desktop';
      %{ endif }

  - path: /opt/guacamole/install.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      exec > /var/log/guacamole-setup.log 2>&1
      echo "$(date): Starting Guacamole installation..."

      # Install Docker
      curl -fsSL https://get.docker.com | sh
      systemctl enable docker
      systemctl start docker

      # Wait for Docker to be ready
      echo "$(date): Waiting for Docker..."
      sleep 10
      docker info

      # Create initdb directory
      mkdir -p /opt/guacamole/initdb

      # Generate Guacamole database schema FIRST (before starting containers)
      echo "$(date): Generating Guacamole database schema..."
      docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > /opt/guacamole/initdb/01-schema.sql

      # Verify schema was generated
      if [ ! -s /opt/guacamole/initdb/01-schema.sql ]; then
        echo "ERROR: Failed to generate database schema!"
        exit 1
      fi
      echo "$(date): Schema generated, size: $(wc -l < /opt/guacamole/initdb/01-schema.sql) lines"

      # Copy connection setup SQL
      cp /opt/guacamole/setup-connections.sql /opt/guacamole/initdb/02-connections.sql

      # Now start the Guacamole stack (PostgreSQL will initialize with the schema)
      echo "$(date): Starting Guacamole containers..."
      cd /opt/guacamole
      docker compose up -d

      # Wait for containers to be healthy
      echo "$(date): Waiting for containers to be ready..."
      sleep 30

      # Verify database initialization
      echo "$(date): Verifying database..."
      docker exec guacamole_db psql -U guacamole -d guacamole_db -c '\dt' || echo "Warning: Could not verify tables"

      echo "$(date): Guacamole installation completed!"
      echo "Access Guacamole at http://$(hostname -I | awk '{print $1}'):8080/guacamole"
      echo "Default credentials: guacadmin / guacadmin"

runcmd:
  - mkdir -p /opt/guacamole
  - chmod +x /opt/guacamole/install.sh
  - /opt/guacamole/install.sh
