#cloud-config

users:
  - name: root
    lock_passwd: false

chpasswd:
  expire: false
  users:
    - name: root
      password: "${root_password}"
  encrypted: false

ssh_pwauth: true

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git
  - curl
  - jq

write_files:
  - path: /opt/mailcow/mailcow.conf
    permissions: '0600'
    content: |
      MAILCOW_HOSTNAME=${hostname}
      MAILCOW_TZ=Europe/Zurich
      DBNAME=mailcow
      DBUSER=mailcow
      DBPASS=${api_key}
      DBROOT=${api_key}
      HTTP_PORT=80
      HTTP_BIND=0.0.0.0
      HTTPS_PORT=443
      HTTPS_BIND=0.0.0.0
      SMTP_PORT=25
      SMTPS_PORT=465
      SUBMISSION_PORT=587
      IMAP_PORT=143
      IMAPS_PORT=993
      POP_PORT=110
      POPS_PORT=995
      SIEVE_PORT=4190
      DOVEADM_PORT=127.0.0.1:19991
      SQL_PORT=127.0.0.1:13306
      SOLR_PORT=127.0.0.1:18983
      REDIS_PORT=127.0.0.1:7654
      API_KEY=${api_key}
      API_KEY_READ_ONLY=
      API_ALLOW_FROM=0.0.0.0/0
      SKIP_LETS_ENCRYPT=y
      SKIP_SOGO=n
      SKIP_CLAMD=y
      SKIP_SOLR=y
      COMPOSE_PROJECT_NAME=mailcow
      ADDITIONAL_SAN=

  - path: /opt/swiss365/agent.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """Swiss365 Server Agent - Receives commands via webhook"""
      import http.server
      import json
      import subprocess
      import os
      import hashlib
      import hmac

      AGENT_SECRET = "${api_key}"
      PORT = 9365

      class AgentHandler(http.server.BaseHTTPRequestHandler):
          def verify_signature(self, body):
              sig = self.headers.get('X-Swiss365-Signature', '')
              expected = hmac.new(
                  AGENT_SECRET.encode(),
                  body,
                  hashlib.sha256
              ).hexdigest()
              return hmac.compare_digest(sig, expected)

          def do_POST(self):
              content_length = int(self.headers['Content-Length'])
              body = self.rfile.read(content_length)
              
              if not self.verify_signature(body):
                  self.send_response(403)
                  self.end_headers()
                  self.wfile.write(b'Invalid signature')
                  return

              try:
                  data = json.loads(body)
                  action = data.get('action')
                  
                  if action == 'status':
                      result = subprocess.run(
                          ['docker', 'ps', '--format', 'json'],
                          capture_output=True, text=True
                      )
                      response = {'status': 'ok', 'containers': result.stdout}
                  
                  elif action == 'restart':
                      service = data.get('service', 'all')
                      if service == 'all':
                          subprocess.run(['docker-compose', '-f', '/opt/mailcow/docker-compose.yml', 'restart'])
                      else:
                          subprocess.run(['docker-compose', '-f', '/opt/mailcow/docker-compose.yml', 'restart', service])
                      response = {'status': 'ok', 'message': f'Restarted {service}'}
                  
                  elif action == 'health':
                      result = subprocess.run(['curl', '-s', 'http://localhost/api/v1/get/status/containers'], capture_output=True, text=True)
                      response = {'status': 'ok', 'health': result.stdout}
                  
                  else:
                      response = {'status': 'error', 'message': 'Unknown action'}

                  self.send_response(200)
                  self.send_header('Content-Type', 'application/json')
                  self.end_headers()
                  self.wfile.write(json.dumps(response).encode())
              
              except Exception as e:
                  self.send_response(500)
                  self.end_headers()
                  self.wfile.write(str(e).encode())

          def do_GET(self):
              if self.path == '/health':
                  self.send_response(200)
                  self.send_header('Content-Type', 'application/json')
                  self.end_headers()
                  self.wfile.write(b'{"status":"healthy","service":"mailcow"}')
              else:
                  self.send_response(404)
                  self.end_headers()

      if __name__ == '__main__':
          server = http.server.HTTPServer(('0.0.0.0', PORT), AgentHandler)
          print(f'Swiss365 Agent running on port {PORT}')
          server.serve_forever()

  - path: /etc/systemd/system/swiss365-agent.service
    content: |
      [Unit]
      Description=Swiss365 Server Agent
      After=network.target docker.service

      [Service]
      Type=simple
      ExecStart=/usr/bin/python3 /opt/swiss365/agent.py
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Notify installation start
  - |
    SERVER_IP=$(hostname -I | awk '{print $1}')
    curl -s -X POST "https://zelbakpcnbdkygzvxtrj.supabase.co/functions/v1/installation-callback" \
      -H "Content-Type: application/json" \
      -d "{\"server_ip\":\"$SERVER_IP\",\"server_type\":\"mailcow\",\"status\":\"installing\",\"step\":\"docker\",\"progress\":10,\"details\":\"Starting Docker\"}" 2>/dev/null || true

  # Enable Docker
  - systemctl enable docker
  - systemctl start docker

  # Notify Mailcow clone start
  - |
    SERVER_IP=$(hostname -I | awk '{print $1}')
    curl -s -X POST "https://zelbakpcnbdkygzvxtrj.supabase.co/functions/v1/installation-callback" \
      -H "Content-Type: application/json" \
      -d "{\"server_ip\":\"$SERVER_IP\",\"server_type\":\"mailcow\",\"status\":\"installing\",\"step\":\"clone\",\"progress\":30,\"details\":\"Cloning Mailcow repository\"}" 2>/dev/null || true

  # Clone and setup Mailcow
  - cd /opt && git clone https://github.com/mailcow/mailcow-dockerized.git mailcow-install
  - cp /opt/mailcow/mailcow.conf /opt/mailcow-install/mailcow.conf

  # Notify pulling images
  - |
    SERVER_IP=$(hostname -I | awk '{print $1}')
    curl -s -X POST "https://zelbakpcnbdkygzvxtrj.supabase.co/functions/v1/installation-callback" \
      -H "Content-Type: application/json" \
      -d "{\"server_ip\":\"$SERVER_IP\",\"server_type\":\"mailcow\",\"status\":\"installing\",\"step\":\"images\",\"progress\":50,\"details\":\"Pulling Docker images\"}" 2>/dev/null || true

  - cd /opt/mailcow-install && docker-compose pull

  # Notify starting containers
  - |
    SERVER_IP=$(hostname -I | awk '{print $1}')
    curl -s -X POST "https://zelbakpcnbdkygzvxtrj.supabase.co/functions/v1/installation-callback" \
      -H "Content-Type: application/json" \
      -d "{\"server_ip\":\"$SERVER_IP\",\"server_type\":\"mailcow\",\"status\":\"configuring\",\"step\":\"containers\",\"progress\":70,\"details\":\"Starting containers\"}" 2>/dev/null || true

  - cd /opt/mailcow-install && docker-compose up -d

  # Start Swiss365 Agent
  - mkdir -p /opt/swiss365
  - systemctl daemon-reload
  - systemctl enable swiss365-agent
  - systemctl start swiss365-agent

  # Open firewall ports
  - ufw allow 25/tcp    # SMTP
  - ufw allow 465/tcp   # SMTPS
  - ufw allow 587/tcp   # Submission
  - ufw allow 143/tcp   # IMAP
  - ufw allow 993/tcp   # IMAPS
  - ufw allow 80/tcp    # HTTP
  - ufw allow 443/tcp   # HTTPS
  - ufw allow 9365/tcp  # Agent
  - ufw --force enable

  # Notify completion
  - |
    SERVER_IP=$(hostname -I | awk '{print $1}')
    curl -s -X POST "https://zelbakpcnbdkygzvxtrj.supabase.co/functions/v1/installation-callback" \
      -H "Content-Type: application/json" \
      -d "{\"server_ip\":\"$SERVER_IP\",\"server_type\":\"mailcow\",\"status\":\"ready\",\"step\":\"complete\",\"progress\":100,\"details\":\"Mailcow installation complete\"}" 2>/dev/null || true
